server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/enrollments/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
